// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactsDocumentDataSlicesSlice = never;

/**
 * Content for Contacts documents
 */
interface ContactsDocumentData {
  /**
   * Slice Zone field in *Contacts*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactsDocumentDataSlicesSlice> /**
   * Meta Description field in *Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contacts.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contacts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contacts.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contacts document from Prismic
 *
 * - **API ID**: `contacts`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactsDocumentData>,
    "contacts",
    Lang
  >;

type FaqsDocumentDataSlicesSlice = never;

/**
 * Content for FAQs documents
 */
interface FaqsDocumentData {
  /**
   * Slice Zone field in *FAQs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqsDocumentDataSlicesSlice> /**
   * Meta Description field in *FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faqs.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faqs.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * FAQs document from Prismic
 *
 * - **API ID**: `faqs`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FaqsDocumentData>, "faqs", Lang>;

type HomepageDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for IPhone documents
 */
interface IphoneDocumentData {
  /**
   * Title field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Model field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.model
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  model: prismic.KeyTextField;

  /**
   * Price field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * Screen diagonal field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.screen_diagonal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  screen_diagonal: prismic.KeyTextField;

  /**
   * Display resolution field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.display_resolution
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  display_resolution: prismic.KeyTextField;

  /**
   * Matrix type field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.matrix_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  matrix_type: prismic.KeyTextField;

  /**
   * Screen refresh rate field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.screen_refresh_rate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  screen_refresh_rate: prismic.KeyTextField;

  /**
   * Screen material field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.screen_material
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  screen_material: prismic.KeyTextField;

  /**
   * Number of SIM cards field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.number_of_sim_cards
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_of_sim_cards: prismic.KeyTextField;

  /**
   * SIM card dimensions field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.sim_card_dimensions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sim_card_dimensions: prismic.KeyTextField;

  /**
   * Built in memory field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.built_in_memory
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  built_in_memory: prismic.KeyTextField;

  /**
   * Front camera field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.front_camera
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  front_camera: prismic.KeyTextField;

  /**
   * Type of frontal flash field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.type_of_frontal_flash
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type_of_frontal_flash: prismic.KeyTextField;

  /**
   * Front camera video recording field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.front_camera_video_recording
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  front_camera_video_recording: prismic.KeyTextField;

  /**
   * Name of the processor field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.name_of_the_processor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_of_the_processor: prismic.KeyTextField;

  /**
   * Number of cores field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.number_of_cores
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_of_cores: prismic.KeyTextField;

  /**
   * Main camera field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.main_camera
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_camera: prismic.KeyTextField;

  /**
   * Record video of the main camera field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.record_video_of_the_main_camera
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  record_video_of_the_main_camera: prismic.KeyTextField;

  /**
   * Connectors field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.connectors
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  connectors: prismic.KeyTextField;

  /**
   * Weight field in *IPhone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iphone.weight
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  weight: prismic.KeyTextField;
}

/**
 * IPhone document from Prismic
 *
 * - **API ID**: `iphone`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IphoneDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<IphoneDocumentData>, "iphone", Lang>;

type ServicesDocumentDataSlicesSlice = never;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Icon field in *Settings → Navigation*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"IPhone" | "IPad" | "Mac" | "Watch" | "Headphones">;
}

/**
 * Item in *Settings → PagesNavigation*
 */
export interface SettingsDocumentDataPagesnavigationItem {
  /**
   * Link field in *Settings → PagesNavigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.pagesnavigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → PagesNavigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.pagesnavigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * PagesNavigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.pagesnavigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pagesnavigation: prismic.GroupField<
    Simplify<SettingsDocumentDataPagesnavigationItem>
  >;

  /**
   * Homepage field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.homepage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  homepage: prismic.LinkField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ContactsDocument
  | FaqsDocument
  | HomepageDocument
  | IphoneDocument
  | ServicesDocument
  | SettingsDocument;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactsDocument,
      ContactsDocumentData,
      ContactsDocumentDataSlicesSlice,
      FaqsDocument,
      FaqsDocumentData,
      FaqsDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      IphoneDocument,
      IphoneDocumentData,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataPagesnavigationItem,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
    };
  }
}
